apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: bechtle-web
  name: bechtle-web
  namespace: bechtle
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bechtle-web
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bechtle-web
    spec:
      containers:
      - image: quay.io/t_koch/bechtle-web:v3.0
        name: bechtle-web
        resources: {}
